# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/myfastai',
                'doc_host': 'https://sslearnai.github.io',
                'git_url': 'https://github.com/sslearnai/myfastai',
                'lib_path': 'myfastai'},
  'syms': {'myfastai.core': {'myfastai.core.foo': ('core.html#foo', 'myfastai/core.py')}}}
